- src/foremast/pipeline/construct_pipeline_block.py
- tests/pipeline/test_provider_healthcheck.py
Resolves a FIXME that has needed to be done for now. Now that
scaffolding is in place, use that to set the option.
See also: PSOBAT-2465
> fix: Use provider HC when Eureka enabled

- src/foremast/awslambda/awslambda.py
Need to compensate for lag in IAM Role Policy changes.
See also: #50
> fix: Add retry to Lambda creation

- src/foremast/templates/configs/configs.json.j2
> added lambda_triggers as an empty list

- README.rst
Robert asked that we add a link to the Foremast blog posts to the README to help drive some traffic there.
> added blog post to read me. Will update with future posts

- src/foremast/templates/pipeline/stage-deploy.json.j2
> fix: Default max ASGs for redblack deployments

- README.rst
How do you feel about logo size and placement?
Looks like alignment does not work in Github RST, so I can not figure out how to make the image center.
> Added Logo to README

- src/foremast/templates/infrastructure/iam/lambda.json.j2
> Added lambda IAM permission to log by default

- src/foremast/templates/infrastructure/iam/elasticsearch.json.j2
Fixes #76 
I think this is what you are looking for. Doesn't make much sense (to me) to limit Resource: to a specific domain.
> feat: ElasticSearch IAM template

- src/foremast/consts.py
For some reason we weren't resolving the paths.
> fix: Expand certificate paths

- _docs/configuration_files/foremast_config.rst
- _docs/configuration_files/pipeline_json/services.rest
- Mentioned you can also provide a list of bucket names
> Updated documentation around s3 buckets

- src/foremast/utils/lookups.py
- tests/utils/test_file_lookups.py
- tests/utils/test_git_lookups.py
Manual Pipelines will need to retrieve Pipeline JSON definition files from Git. This provides a concise way to grab the file and will be useful for refactoring `process_git_configs()` in [src/foremast/configs/prepare_configs.py](https://github.com/gogoair/foremast/blob/master/src/foremast/configs/prepare_configs.py).
See also: #72
> feat: Provide centralized Git file retrieval

- src/foremast/templates/infrastructure/iam/firehose.json.j2
There seems to be a lot of things associated with Firehose, so any help with understanding what else would be required will be appreciated.
Fixes: #70
> feat: Kinesis Firehose IAM template

- src/foremast/configs/prepare_configs.py
Switch local and remote file lookups to use the centralized Class `FileLookup` in #74.
See also: #72
> refactor: Use new central FileLookup

- tox.ini
noticed when tox was running, it was attempting to run all the tests in my local virtualenv. Fixed it to just do foremast specific tests.
> Updated tests to use the tests/ directory specifically

- setup.py
- src/foremast/__main__.py
- src/foremast/args.py
- src/foremast/consts.py
- src/foremast/runner.py
This provides a more explorable CLI structure. Try to ignore the configuration spew for now, we'll need to clean up the side effect of importing `foremast.consts` eventually.
``` bash
$ foremast
No configuration found in the following locations:
/etc/foremast/foremast.cfg
/home/ntangsurat/.foremast/foremast.cfg
./.foremast/foremast.cfg
Section missing from configurations: [base]
[base] missing key "gate_api_url", using None.
[base] missing key "git_url", using None.
[base] missing key "domain", using 'example.com'.
[base] missing key "envs", using ''.
[base] missing key "regions", using ''.
[base] missing key "types", using 'ec2,lambda'.
[base] missing key "templates_path", using None.
[base] missing key "ami_json_url", using None.
[base] missing key "default_ec2_securitygroups", using …
```
> feat: Unified CLI commands

- src/foremast/pipeline/create_pipeline.py
Include the application name in successful pipeline creation message.
> Add application name in successful pipeline message

- _docs/configuration_files/application_json.rst
- src/foremast/awslambda/awslambda.py
- src/foremast/templates/configs/configs.json.j2
- tests/lambda/test_aws.py
Need a way to specify a custom Role to use for Lambda Functions.
> feat: Custom Lambda Role

- src/foremast/awslambda/cloudwatch_event/cloudwatch_event.py
- src/foremast/utils/awslambda.py
This should fix an issue where events may not be added to the correct lambda method.
> Fix lambda events

- src/foremast/templates/infrastructure/iam/emr.json.j2
added ElasticMapReduce permissions to our policy templates
> added emr policy to templates

- tests/dns/test_dns.py
- tests/iam/test_iam_construct.py
I was having to rename my local config for tests to work with default values. I mocked these defaults and now tests still work with out changing local foremast configs.
> mocked config values so that it works with local foremast configs

- src/foremast/runner.py
- src/foremast/s3/s3apps.py
- src/foremast/templates/configs/configs.json.j2
Do you think website should be enabled or disabled by default?
> added S3 website settings for making a bucket serve static content

- src/foremast/exceptions.py
- src/foremast/s3/s3deploy.py
This fixes a bug where you could upload an empty directory and that would then sync to LATEST, basically removing LATEST.
> Catches problems with empty or missing artifact path.

- src/foremast/templates/configs/pipeline.json.j2
Remove a duplicate key in the `pipeline.json.j2` template file.
> Remove duplicate key

- src/foremast/templates/infrastructure/iam/kinesis.json.j2
Devs want the ability to have permission to specific kinesis streams. Exposing the interface for them.
> Added support for kinesis in Application JSON

- src/foremast/s3/s3deploy.py
AWS does not have a feature for s3 bucket to bucket time based sync. We are placing cp command first then sync so our sync works as expected.
> Adding recursive cp before s3 sync

- _docs/configuration_files/application_json.rst
- src/foremast/elb/create_elb.py
- src/foremast/templates/configs/configs.json.j2
- src/foremast/templates/infrastructure/elb_data.json.j2
Adding support for users to add elb idle connection timeouts as well as specify connection draining.
> Enable modification of ELB attributes such as draining and timeouts

- _docs/configuration_files/foremast_config.rst
- src/foremast/consts.py
- src/foremast/templates/configs/config.py.example
- src/foremast/templates/configs/foremast.cfg.example
We are now able to load a python file 'config.py' as a source of
configuration details.
> feat: Add ability to use a dynamic config

- src/foremast/elb/create_elb.py
We had log statements referencing variables before they were set.
> Place log statements variable references after variables.

- .travis.yml
- tox.ini
Prospector has fixed the issues in their latest release.
Fix: https://github.com/landscapeio/prospector/pull/207
Release: https://pypi.python.org/pypi/prospector/0.12.5
> fix: Re-enable linting

- _docs/requirements-docs.txt
This should fix the builds in readthedocs.
> fix: Make readthedocs work again

- src/foremast/templates/infrastructure/autoscaling_policy.json.j2
> added conditional to autoscaling templates to fix issue with decrease policies

- src/foremast/awslambda/awslambda.py
Misplaced tag option, now corrected.
> Move tagging to create lambda from update.

- .travis.yml
This simplifies the travis config file.
It is simpler to manage an includes vs excludes.
> test: Simplify travis config

- _docs/getting_started.rst
> docs: Fix typo

- src/foremast/runner.py
- src/foremast/s3/__main__.py
- src/foremast/s3/s3apps.py
> S3 Tagging

- src/foremast/exceptions.py
Mainly innocuous linting issues.
> fix: Clean up exceptions linting issues

- _docs/configuration_files/pipeline_json/services.rest
- src/foremast/templates/infrastructure/iam/cloudwatch.json.j2
We had a request from some developers being able to send metrics to cloudwatch from kinesis streams.
> Iam/cloudwatch limited access.

- src/foremast/pipeline/construct_pipeline_block.py
makes it so we can access anything in pipeline.json from templates
> pass all pipeline data to templates

- src/foremast/securitygroup/create_securitygroup.py
- tests/test_securitygroup.py
Minor enhancement adding tags to the security groups.
> Add tagging to security groups

- requirements.txt
- src/foremast/app/__main__.py
- src/foremast/app/aws.py
- src/foremast/app/base.py
- src/foremast/args.py
- src/foremast/common/base.py
- src/foremast/exceptions.py
- src/foremast/plugin_manager.py
- src/foremast/runner.py
- tests/app/test_create_app.py
This a sample of how we can split an service into plugins.
Its a little rough but it should work.
> Create app split to plugin

- src/foremast/utils/templates.py
Document and clean up template retrieval errors.
> fix: Improve template retrieval errors

- src/foremast/securitygroup/create_securitygroup.py
This removes that restriction when checking the cidr in a security group.
> Remove security group restriction

- src/foremast/securitygroup/create_securitygroup.py
- tests/test_securitygroup.py
Try and simplify creating security group code.
This should make it more testable.
Depends on #256.
> Refactor security group ingress rule

- src/foremast/autoscaling_policy/create_policy.py
- src/foremast/awslambda/api_gateway_event/api_gateway_event.py
- src/foremast/awslambda/awslambda.py
- src/foremast/awslambda/awslambdaevent.py
- src/foremast/configs/outputs.py
- src/foremast/utils/properties.py
- tests/lambda/test_aws.py
- tests/lambda/test_event.py
Update lambda and autoscaling to use region-specific configs. If we are cool with these updates, I will do the same for all other services but wanted to start small.
> Use region specific configs - Lambda and autoscaling 

- src/foremast/utils/lookups.py
We previously allowed `Lookup()` to not throw exceptions when a file was not found.
After updating to use Gitlab V4 API that behavior changed.
This ensures we keep the expected behavior.
Before change
```
2018-02-23 15:28:47,568 [INFO] foremast.utils.lookups:remote_file:186 - Retrieving "runway/application-master-build.json" from "forrest/edge".
Traceback (most recent call last):
File "/home/saviles/.local/share/virtualenvs/foremast-JzqYWaaJ/lib/python3.6/site-packages/gitlab/exceptions.py", line 247, in wrapped_f
return f(*args, **kwargs)
File "/home/saviles/.local/share/virtualenvs/foremast-JzqYWaaJ/lib/python3.6/site-packages/gitlab/mixins.py", line 48, in get
server_data = self.gitlab.http_get(path, **kwargs)
File "/home/saviles/.local/share/virtualenvs/foremast-JzqYWaaJ/lib/python3.6/ …
```
> Fix config processing

- src/foremast/datapipeline/datapipeline.py
- src/foremast/dns/create_dns.py
- src/foremast/elb/create_elb.py
- src/foremast/s3/s3apps.py
- src/foremast/s3/s3deploy.py
- src/foremast/securitygroup/create_securitygroup.py
- tests/datapipeline/test_datapipeline.py
Updates the datapipeline, DNS, S3, Security Groups, and ELB services in Foremast to use region specific configs
> updated to use region specific configs

- _docs/configuration_files/application_json.rst
- _docs/configuration_files/index.rst
- _docs/configuration_files/region_overrides.rst
- src/foremast/pipeline/create_pipeline.py
- src/foremast/pipeline/create_pipeline_datapipeline.py
- src/foremast/pipeline/create_pipeline_lambda.py
- src/foremast/pipeline/create_pipeline_s3.py
- tests/pipeline/test_create_pipeline.py
Finishes region specific configs and makes sure the pipeline is updated. 
Contains changes from #273 so review that PR first
> Pipeline region specific

- _docs/configuration_files/application_json.rst
- src/foremast/templates/infrastructure/autoscaling_policy.json.j2
- Delay between new instance coming up and metrics feeding into ASG
Aggregate metrics
> Added support for instance_warmup

- _docs/configuration_files/pipeline_json/lambda.rest
Update lambda docs to include all valid runtime strings
> docs: add all runtime strings

- _docs/configuration_files/s3.rest
- src/foremast/s3/s3apps.py
- src/foremast/templates/configs/configs.json.j2
Adds support for versioning s3 buckets and logging access requests to s3 buckets.
> feat: Versioning and Logging for S3 Deployments

- src/foremast/consts.py
The amount of time I wasted tracking this down was TOO HIGH! This at least lets folks know when their config is bad with a clear error in the logs. Most likely will need a long term refactor but this is a good start.
> Added ImportError logging issues with reading dynamic config

- _docs/configuration_files/pipeline_json/services.rest
- src/foremast/templates/infrastructure/iam/xray.json.j2
Also documented some missing services.
> Added support for AWS XRay in Services Block

- src/foremast/consts.py
- src/foremast/exceptions.py
With Fiat enabled, we need to handle if a Task fails due to permissions.
```python
{'application': 'ntangsuratunicorn7',
'buildTime': 1527867929060,
'endTime': 1527867929725,
'execution': {'application': 'ntangsuratunicorn7',
'authentication': {'allowedAccounts': ['artifactory',
'dockerhub',
'preprod',
'services',
'dev',
'serviceskubernetes',
'stage'],
'user': 'foremast@upgrade.com'},
'buildTime': 1527867929060,
'canceled': False,
'canceledBy': None,
'cancellationReason': None,
'description': 'Created application ntangsuratunicorn7',
'endTime': 1527867929725,
'id': '8ea3dad4-175b-49fa-97be-7bf3b5ff0500',
'initialConfig': {},
'keepWaitingPipelines': False,
'limitConcurrent': False,
'name': None,
'notifications': [],
'origin': 'api',
'paused': None,
'pipelineConfigId': None,
'stages': …
```
> fix: Task Error Handling

- .travis.yml
- setup.py
- tox.ini
Yes, I know. Sudo. Read here:
https://github.com/travis-ci/travis-ci/issues/9815
> Added initial Python 3.7 support

- tox.ini
This should fix the linting tests failures in CI.
> test: Fix failed linting checks

- src/foremast/app/create_app.py
- tests/app/test_create_app.py
This passes `DEFAULT_RUN_AS_USER` and `formats` to `app_data.json.j2` template, which is used when creating an app.
> Feature: Send additional data to create_app templates

- src/foremast/pipeline/construct_pipeline_block.py
- src/foremast/pipeline/construct_pipeline_block_lambda.py
- src/foremast/utils/encoding.py
Need a way to access the standard name generator in User Data.
> fix: Expose Generator to User Data

- src/foremast/consts.py
Support setting the dynamic configuration file to use using the
environment variable `FOREMAST_CONFIG_FILE`.
> feat: Environment variable FOREMAST_CONFIG_FILE

- _docs/configuration_files/application_json.rst
- src/foremast/runner.py
- src/foremast/templates/configs/configs.json.j2
Not everyone uses archaius in the community, let alone uses an application.properties. This at least converts this logic to a toggle until this can be investigated further in a future release.
> Converted Archaius to feature toggle to remove assumption of internal logic

- src/foremast/pipeline/construct_pipeline_block.py
- src/foremast/pipeline/create_pipeline.py
- src/foremast/pipeline/create_pipeline_datapipeline.py
- src/foremast/pipeline/create_pipeline_lambda.py
- src/foremast/pipeline/create_pipeline_s3.py
Just adding the ability to pass the generated repo name to templates. Basically feature parity with other templates.
> feat: Ability to pass repo_name and group_name to trigger

- _docs/configuration_files/pipeline_json/services.rest
- src/foremast/templates/infrastructure/iam/kms.json.j2
- src/foremast/templates/infrastructure/iam/secretsmanager.json.j2
Adding support for using AWS Secrets Manager.
> feat: Adding support for AWS Secrets Manager

- src/foremast/templates/configs/configs.json.j2
> Fixed lambda environment default

- _docs/configuration_files/s3.rest
- src/foremast/s3/s3apps.py
- src/foremast/templates/configs/configs.json.j2
Adding support for S3 Bucket Event Notifications.
https://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html
> feat: Added support for S3 Bucket Notification Configurations

- _docs/configuration_files/application_json.rst
- src/foremast/autoscaling_policy/create_policy.py
- src/foremast/templates/configs/configs.json.j2
This enables developers to specify the amount to scale up and down by in their application.json files.
> feat: Added support to increment/decrement by custom amounts in scaling policies

- requirements.txt
- src/foremast/app/__main__.py
- src/foremast/app/aws.py
- src/foremast/app/base.py
- src/foremast/args.py
- src/foremast/common/base.py
- src/foremast/exceptions.py
- src/foremast/plugin_manager.py
- src/foremast/runner.py
- tests/app/test_create_app.py
@sijis has a fairly stable Branch going for the new Plugin system. This should be a relatively safe switch over.
> feat: Initial Plugin infrastructure for Application creation

- _docs/configuration_files/application_json.rst
- _docs/configuration_files/datapipeline.rest
- _docs/configuration_files/example-qe.json.j2
- _docs/configuration_files/qe.rest
- Some questions as to what this is used for. Added some example keys
that could be used to achieve quality testing.
- Highlight the fact that this is customizable per company
Cleaned up also blocks in application_json for now.
> docs: Added support explaining the undocumented QE Block

- src/foremast/consts.py
- src/foremast/templates/configs/config.py.example
- src/foremast/utils/vpc.py
Trying to solve older issues:
https://github.com/foremast/foremast/issues/189
This should solve it, and allow folks to override the vpc name in the config.py
> feat: Ability to change VPC name when looking up VPC ID

- _docs/configuration_files/foremast_config.rst
> Added docs for FOREMAST_CONFIG_FILE

- .travis.yml
- src/foremast/__init__.py
- src/foremast/app/base.py
- src/foremast/app/create_app.py
- src/foremast/autoscaling_policy/create_policy.py
- src/foremast/awslambda/__init__.py
- src/foremast/awslambda/awslambdaevent.py
- src/foremast/awslambda/event_source_mapping/event_source_mapping.py
- src/foremast/consts.py
- src/foremast/pipeline/__init__.py
- src/foremast/pipeline/clean_pipelines.py
- src/foremast/pipeline/create_pipeline.py
- src/foremast/pipeline/create_pipeline_datapipeline.py
- src/foremast/pipeline/create_pipeline_lambda.py
- src/foremast/pipeline/create_pipeline_manual.py
- src/foremast/pipeline/create_pipeline_s3.py
- src/foremast/runner.py
- src/foremast/securitygroup/destroy_sg/destroy_sg.py
- src/foremast/utils/apps.py
- src/foremast/utils/dynamodb_stream.py
- src/foremast/utils/elb.py
- src/foremast/utils/gate.py
- src/foremast/utils/google_iap.py
- src/foremast/utils/kayenta.py
- src/foremast/utils/security_group.py
- src/foremast/utils/subnets.py
- src/foremast/utils/tasks.py
- src/foremast/utils/vpc.py
- tox.ini
Fix the isort warnings from https://github.com/foremast/foremast/pull/368.
> Fix: File imports

- .travis.yml
- tox.ini
This adds an isort check to the lint check.
> chore: Add isort checks

- _docs/configuration_files/application_json.rst
- src/foremast/awslambda/awslambda.py
- src/foremast/templates/configs/configs.json.j2
- tests/lambda/test_aws.py
- tests/lambda/test_event.py
Currently tracing and debugging of lambda is difficult. By adding support for lambda tracing this will add the AWS X-Ray APIs to be able to perform an inspection of the function and breakdown of what items are causing a function to take time.
> feat: Adding Lambda Tracing Capabilities

- src/foremast/pipeline/create_pipeline_manual.py
Resolves issue 367 by raising exception in event of templates path not being set.
> raise exception when no templates dir set

- src/foremast/utils/asg.py
Fixed index format string from 0 to 1. Only index zero is available in the current context.
> Fixed asg index indicator

- .travis.yml
- tox.ini
Python 3.8 came out 2 days ago, seeing how our code base handles it with tests. :)
> Added Python 3.8 support to tests

- src/foremast/awslambda/event_source_mapping/event_source_mapping.py
https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html
> hotfix: SQS Event Source does not require starting position.

- _docs/lambda/lambda_events.rst
- src/foremast/awslambda/event_source_mapping/event_source_mapping.py
- Fixed issue where SQS Lambda event trigger Update function was passing unsupported parameter, and failing with keyError.
- Added Lambda  Event trigger parameters options:
BisectBatchOnFunctionError
MaximumRetryAttempts
DestinationConfig
> Lambda events: fixed sqs update, and added options to kinesis

- src/foremast/pipeline/jinja_functions.py
Changes:
* Adds a helper function for raising an error/exception
* Avoids the need for a Jinja plugin
Use in a Jinja template:
```jinja
{{ raise_exception('You did a bad thing!') }}
```
Results in a stack trace ending like:
```
raise Exception(message)
Exception: You did a bad thing!
```
> feat: Added raise exception helper to Jinja functions

- _docs/configuration_files/application_json.rst
- src/foremast/autoscaling_policy/create_policy.py
- src/foremast/awslambda/awslambda.py
- src/foremast/templates/configs/configs.json.j2
- src/foremast/utils/kayenta.py
- tests/lambda/test_aws.py
- tests/lambda/test_event.py
> feat: adding support for efs in lambda

- src/foremast/gcp_iam/create_iam_resources.py
* Fixes bug causing KeyError during foremast infra step for some GCP pipelines
> fix: KeyError gcp_roles during GCP IAM step

- src/foremast/gcp_iam/create_iam_resources.py
GCP returns a 409 Conflict code when IAM resources are edited simultaneously.  GCP IAM can be a bit slow while it replicates changes globally.  This can lead to Foremast infra step failures when a pipeline is running twice in parallel.
Changes:
* Added exponential backoff with 5 max tries on creating svc accounts (this matches how we handle policy updates already)
* Added additional debug logging when checking for existing svc accounts
> fix: automatic retry on GCP svc account creation failure

- _docs/configuration_files/application_json.rst
- src/foremast/awslambda/awslambda.py
- src/foremast/templates/configs/configs.json.j2
- tests/lambda/test_aws.py
- tests/lambda/test_event.py
> feat: allowing for provisioned throughput of lambda

- src/foremast/gcp_iam/create_iam_resources.py
- src/foremast/utils/google_iap.py
Just adding missing headers to a few contributions 👍
> fix: Added Missing Licenses on contributions

- _docs/lambda/lambda_events.rst
- src/foremast/awslambda/event_source_mapping/event_source_mapping.py
For Kinesis Triggers, allow the ability to increase parallelization and also set timestamp AT_TIMESTAMP
> feat: Added starting_position_timestamp and parallelization_factor

- _docs/configuration_files/pipeline_json/services.rest
- src/foremast/templates/infrastructure/iam/mediaconvert.json.j2
> feat: Added MediaConvert to Services Block

- src/foremast/awslambda/event_source_mapping/event_source_mapping.py
Due to timestamp default, AWS API was rejecting trigger creates/updates.
> fix: Fixed an issue where setting LATEST or TRIM_HORIZON would fail

- _docs/configuration_files/application_json.rst
- _docs/configuration_files/pipeline_json/index.rst
- _docs/configuration_files/pipeline_json/services.rest
- _docs/configuration_files/stepfunction.rest
- src/foremast/awslambda/awslambda.py
- src/foremast/consts.py
- src/foremast/exceptions.py
- src/foremast/pipeline/construct_pipeline_block_stepfunction.py
- src/foremast/pipeline/create_pipeline_stepfunction.py
- src/foremast/runner.py
- src/foremast/s3/s3apps.py
- src/foremast/stepfunction/__init__.py
- src/foremast/stepfunction/stepfunction.py
- src/foremast/templates/configs/configs.json.j2
- src/foremast/templates/infrastructure/iam/trust/stepfunction_role.json.j2
- src/foremast/templates/pipeline/pipeline_prod_stepfunction.json.j2
- src/foremast/templates/pipeline/pipeline_stages_stepfunction.json.j2
- src/foremast/templates/pipeline/pipeline_wrapper.json.j2
- src/foremast/templates/pipeline/stage-infrastructure-setup-stepfunction.json.j2
Adding support for AWS StepFunction pipelines.
> AWS StepFunction Pipeline Support

- _docs/configuration_files/example-qe.json.j2
- _docs/configuration_files/qe.rest
The quality step is possibly open to too much interpretation so we are adding some internal example of how powerful/customizable the Quality Step COULD be.
Again, this template is an example, but every org/user will need to review/modify to their specific spec!
> feat: Update OSS Docs to Highlight Advanced Usages of Quality Step
