setup.py
When `tox` runs, `git describe` fails to generate the version number.
This provides a safe default in the case when the command fails to
generate a version number.
=> fix: Fallback `git describe` string for tox

tests/apigateway/test_api.py
This fixes the test case since at some point the default path for a resource name changed.
=> Fix test cases as default path of api gateway resource changed

src/foremast/pipeline/construct_pipeline_block.py
Forgot to force enable the default Provider Health Check when the
templates have this value defined.
See also: PSOBAT-2365
=> fix: Handle template defined Provider Health Check

_docs/configuration_files/application_json.rst, src/foremast/pipeline/construct_pipeline_block.py, src/foremast/templates/configs/configs.json.j2, src/foremast/templates/pipeline/stage-deploy.json.j2
This fixes #59. This enables modification of default subnet associateIpAddress behavior. By default, it leaves it as `null` or in other words `default`
=> Added support for modifying associatePublicIpAddress

tox.ini
Its probably best to split code and linting tests. A linting check shouldn't necessarily fail a unit test.
=> Split tox into code / lint checks

src/foremast/pipeline/renumerate_stages.py, src/foremast/templates/pipeline/stage-bake.json.j2, src/foremast/templates/pipeline/stage-deploy-lambda.json.j2, src/foremast/templates/pipeline/stage-deploy.json.j2, src/foremast/templates/pipeline/stage-infrastructure-setup-lambda.json.j2, src/foremast/templates/pipeline/stage-infrastructure-setup.json.j2, src/foremast/templates/pipeline/stage-judgement-nonprod.json.j2, src/foremast/templates/pipeline/stage-scaling-policy.json.j2
fixes #58 
I changed the logic to look for `"a"` or `"b"`  in the stage templates. Stages marked with `"a"` are mainline required pipeline stages. stages marked with `"b"` are secondary parallel stages. The order is already handled by https://github.com/gogoair/foremast/blob/master/src/foremast/templates/pipeline/pipeline_stages.json.j2 template.
This change would break existing templates, but makes the enumerate code a lot cleaner and supportable.
I tested this against our current pipeline and it works consistently.
=> Updated renumerate function to remove hardcoded stage names

src/foremast/templates/infrastructure/iam/elasticache.json.j2
Fixes #75 
I'm very well versed in elasticache but this follows what the docs list. The s3 bucket is used when restoring from a snapshot so I'm not sure if that would come in to play for how foremast uses these templates or if it is still needed if not restoring.
=> feat: adding elasticache template

src/foremast/elb/format_listeners.py, src/foremast/exceptions.py, src/foremast/utils/templates.py, tests/test_valid_json_templates.py
Today, Amazon has issues with rotating TLS/SSL certificates in AWS. The workflow is as follows:
1. Create SSL Cert
2. Upload it to AWS with different name
3. Update all references to new certificate
Today, step 3 means every developer will need to update their foremast configs in their individual repos to the latest name. This is fine, but in emergency situations, this can cause a widespread impact. 
With this Pull Request, I want to support the classic way of naming (not to break current users of foremast), and also enable setting of custom certificate names based on a template. We plan on using `<cert_name>-<date_of_expiry>`, but this will enable folks to set whatever naming they want and also even abstract SSL key names to end users so they can specify friendly names as well.
This is …
=> Support IAM TLS Certificate Templates -- Helps with TLS Certificate Rotation

src/foremast/templates/infrastructure/iam/lambda.json.j2
Amazon has mentioned there was an issue in their documentation:
See the new docs here.
http://docs.aws.amazon.com/lambda/latest/dg/policy-templates.html#LambdaVPCAccessExecutionRole
=> Updated lambda policy after AWS addressed a bug in their documentation:

src/foremast/pipeline/create_pipeline.py, src/foremast/templates/pipeline/pipeline_wrapper.json.j2
This fixes an issue where the empty string causes problems in S3.
It tested this against an S3 and Cassanada backend for Front50. Keeping the value None instead of an empty string works in both.
=> Changed pipeline_id to be None if no existing pipeline exists.

_docs/configuration_files/pipeline_json/index.rst, _docs/configuration_files/pipeline_json/manual.rest, src/foremast/pipeline/__init__.py, src/foremast/pipeline/clean_pipelines.py, src/foremast/pipeline/create_pipeline.py, src/foremast/pipeline/create_pipeline_manual.py, src/foremast/runner.py, src/foremast/templates/configs/pipeline.json.j2
When `{"type": "manual"}`, use the listed files in `{"pipeline_files": []}` to create Pipelines.
See also: #74
Closes: #72
=> feat: Manual Pipeline support

src/foremast/pipeline/construct_pipeline_block.py, tests/pipeline/test_provider_healthcheck.py
This was `Amazon` for Eureka deployments but this causes it not to check Eureka healthchecks, only Amazon. Changed default to `Discovery` and this solves the issues. ELB deployments work the same as before.
=> changed default_provider to discovery

src/foremast/exceptions.py, src/foremast/securitygroup/create_securitygroup.py, tests/test_securitygroup.py
When `pipeline.json` is configured with the wrong environments or the Security Group definition is missing in the `application.json`, we should alert with a more informative error.
=> fix: Handle missing env

_docs/configuration_files/pipeline_json/services.rest, src/foremast/templates/infrastructure/iam/elasticsearch.json.j2
It appears ElasticSearch has a bunch of hidden and undocumented IAM permissions. For example,  es:ESHttpGet is one used to do HTTP Get requests against a specified domain. This PR updates the policy to enable users to specify a list of ES Domains as well as give the recommended access as per https://forums.aws.amazon.com/message.jspa?messageID=678366
Docs updated as well as I noticed this was missing as well.
=> Updated ElasticSearch Permissions

src/foremast/templates/infrastructure/iam/firehose.json.j2
There was a typo in the policy for firehose (it was granting dynamo not firehose)
=> Fixed typo in firehose policy template

_docs/conf.py, requirements-dev.txt
Fix docs so they include api details within the 'Foremast Modules" section.
=> fix: Include api details in docs

src/foremast/elb/create_elb.py
I think this was a bug, get_subnets() only ever looked at internet subnets regardless of what was configured.
=> added purpose to get_subnet for elbs

src/foremast/runner.py, src/foremast/templates/configs/configs.json.j2
made it so that when DNS is created the global record and region specific DNS is created. This is configurable but true by default
=> default region specific DNS

src/foremast/pipeline/create_pipeline_manual.py, src/foremast/utils/pipelines.py, tests/test_utils.py, tests/utils/test_string_formatting.py
Need to remove bad characters from the generated Pipeline name in accordance with Spinnaker's name checker. This allows manual Pipelines to be created and deleted properly.
=> fix: Manual pipeline safe name

src/foremast/exceptions.py, src/foremast/pipeline/clean_pipelines.py
Add handling for bad Pipeline deletion request. Gate returns the `method_not_allowed` status code when deleting really cannot be completed, most likely from an improper Pipeline name.
=> fix: Delete Pipeline

src/foremast/utils/dns.py
This is necessary for when applications change to multiregion. An upsert does not work since the record type changes.
=> Added logic for finding and deleting old CNAME records

src/foremast/elb/create_elb.py
As per requested, I added support for setting a LB cookie TTL for stickiness. This defaults to 0 which means no TTL.
I also expanded on the policy name to fix an issue with creating duplicate policies and not allowing a policy to change.
=> added cookie_ttl support and fixed bug with duplicate stickiness policy

src/foremast/elb/create_elb.py
If you include `CookieExpirationPeriod` in the boto3 call with `0` or `None`, it throws an exception.
=> fixed issue with cookie expiration period default

_docs/configuration_files/application_json.rst, _docs/infra_assumptions.rst, src/foremast/elb/create_elb.py, src/foremast/elb/format_listeners.py, src/foremast/templates/configs/configs.json.j2, tests/elb/test_elb.py
- Needed for legacy support for WebSockets where they need to pass to backend systems through ProxyProtocol
- Cleaned up naming of 'policies'; to be specific to 'listenerpolicies' in the foremast config, but in order to not break exisiting functionality, merged policies + listenerpolicies
=> Added support for backend server policies in foremast config

src/foremast/consts.py
Update config logging format so it matches the rest of the output.
**Current**
```
No configuration found in the following locations:
/etc/foremast/foremast.cfg
/home/saviles/.foremast/foremast.cfg
./.foremast/foremast.cfg
Section missing from configurations: [base]
[base] missing key "gate_api_url", using None.
[base] missing key "git_url", using None.
[base] missing key "domain", using 'example.com'.
[base] missing key "envs", using ''.
[base] missing key "regions", using ''.
[base] missing key "types", using 'ec2,lambda,s3'.
[base] missing key "templates_path", using None.
[base] missing key "ami_json_url", using None.
[base] missing key "default_ec2_securitygroups", using ''.
[base] missing key "default_elb_securitygroups", using ''.
Section missing from configurations: [credentials] …
```
=> Format config check logging

src/foremast/autoscaling_policy/create_policy.py
This handles cases where those keys are set as strings
even though we expect integers.
Fixes #100
=> Ensure threshold and period_minutes are integers

_docs/configuration_files/application_json.rst, src/foremast/pipeline/construct_pipeline_block.py, src/foremast/templates/configs/configs.json.j2, src/foremast/templates/pipeline/stage-deploy.json.j2
This will allow users to set their ASG grace period if their application takes longer to boot up than usual. We should consider splitting up into two variables that ultimately calculate hc_grace_period; os_grace_period and app_grace_period.
os_grace_period is usually best known by sysadmins (in regards to average boot time of base operating systems). Development teams would know how long it takes for their container to spin up. Ideally, os_grace_period should be hard coded and maintained by admins to the default time it takes to boot up a raw vanilla server. Devs should then be exposed to enabling only app_grace_period; since they see startup times in their logs.
os_grace_period: 180s
app_grace_period: 40s
hc_grace_period: 220s
=> Support for modifying ASG Grace Period

_docs/configuration_files/application_json.rst, src/foremast/pipeline/construct_pipeline_block.py, src/foremast/templates/configs/configs.json.j2, src/foremast/templates/pipeline/stage-deploy.json.j2
We had an unused app_ssh_key variable in our configs, I moved the key pair to the asg block seeing as that is where it is implemented. Renamed the variable to ssh_keypair.
=> Enabled custom SSH key pairs

src/foremast/elb/create_elb.py
Some JS libraries ship with dots by default in their cookie name, this at least strips it out.
This will fix @willkelleher report of default cookies from Express.
=> Fixed invalid app cookie stickiness policy names

src/foremast/autoscaling_policy/create_policy.py
We have seen some issues with float/ints in this logic and so to eliminate this we will just use the floor and keep it all integers. 
#162
=> [wip] added floor for scaling policy math to keep it all integers

src/foremast/awslambda/awslambda.py
AWS recently added tagging support for lambda. This adds tags for lambda deployments.
=> Tag support for lambda.

_docs/conf.py, setup.py, src/foremast/__main__.py, src/foremast/version.py
Turns out, there was a hidden gem in https://setuptools.readthedocs.io/en/latest/setuptools.html#adding-support-for-revision-control-systems referring to a smart package, https://pypi.python.org/pypi/setuptools_scm.
```bash
$ foremast -v
3.17.2.dev10+gd62004be.d20170518
```
=> refactor: Package version

_docs/configuration_files/pipeline_json/services.rest, _docs/infra_assumptions.rst, src/foremast/templates/infrastructure/iam/elasticache.json.j2, src/foremast/templates/infrastructure/iam/rds-db.j2, src/foremast/templates/infrastructure/iam/rds-db.json.j2
This enables developers to leverage the IAM as auth for RDS in AWS. They need to specify the DB name and DB user such as:
```
"rds-db": {"db_name_here": "username", "another_db_name": "db_user"}
```
Working on docs.
Also unrelated, fixed a typo in elasticache.
=> IAM RDS Connect

src/foremast/awslambda/s3_event/s3_event.py
When a lambda function specifies s3 trigger on a bucket containing `.` character -
```
2017-06-23 20:07:38,220 [DEBUG] foremast.utils.awslambda:add_lambda_permissions:125 - Add permission error: An error occurred (ValidationException) when calling the AddPermission operation: 1 validation error detected: Value 'foremast-deploypss_s3_common.packages.pss.stage.gogoair.com' at 'statementId' failed to satisfy constraint: Member must satisfy regular expression pattern: ([a-zA-Z0-9-_]+)
```
Scrub the SID string of all `.`
=> fix: ensure no  in SID

src/foremast/awslambda/awslambda.py
Currently we only set tags on lambda `create_function`. This adds tag updates to `update_function_configuration`.
If tags exist it will overwrite them without complaint. This lets us skip a check for the existence of these tag keys.
This code wouldn't be needed for people only using lambda deployments after creation tagging was added but it will ensure they remain correct if they are manually changed or removed. 
The documentation for boto's `update_function_configuration` does not include a Tags dict like boto's `create_function` does. Although it's possible this is supported and not documented since Lambda tags are relatively new.
This PR is based off the documented capabilities of boto.
=> feat: on function update also update tags

src/foremast/pipeline/create_pipeline.py, src/foremast/pipeline/create_pipeline_onetime.py
This fixes onetime pipelines for ec2 deployments. Merging in #180 should get close to enabling this for other pipeline types. 
I had to add logic for handling Pipeline ID as this changed in spinnaker since we last used the onetime functionality.
=> fix errors in onetime pipelines for ec2 deployments

src/foremast/exceptions.py, src/foremast/utils/lookups.py, tests/utils/test_file_lookups.py
We observed the stack trace:
```
Traceback (most recent call last):
File "/tmp/workspace/pipes-pipeline-prepare/venv/bin/prepare-infrastructure", line 11, in <module>
sys.exit(prepare_infrastructure())
File "/tmp/workspace/pipes-pipeline-prepare/venv/lib/python3.5/site-packages/foremast/runner.py", line 256, in prepare_infrastructure
runner.write_configs()
File "/tmp/workspace/pipes-pipeline-prepare/venv/lib/python3.5/site-packages/foremast/runner.py", line 75, in write_configs
app_configs = configs.process_git_configs(git_short=self.git_short)
File "/tmp/workspace/pipes-pipeline-prepare/venv/lib/python3.5/site-packages/foremast/configs/prepare_configs.py", line 39, in process_git_configs
file_lookup = FileLookup(git_short=git_short)
File …
```
=> fix: Fail for bad GitLab Project ID lookup

src/foremast/exceptions.py, src/foremast/utils/tasks.py, tests/test_utils.py, tests/utils/tasks/test_check_task.py
`foremast.utils.tasks.check_task()` needs to provide a specific exception when a Spinnaker Task fails to complete in time.
=> fix: Check Task should use a specific exception

src/foremast/s3/s3apps.py, src/foremast/utils/generate_s3_tags.py, tests/s3/test_s3_tags.py
There is a logic to add app_group, app_name tag. S3 api does put tagset which overwrites any other tags that exist in s3 bucket. This logic keeps old tags as well addition to app_group, app_name.
=> Keep old s3 tags when new tags added.

_docs/configuration_files/foremast_config.rst, src/foremast/consts.py, src/foremast/elb/create_elb.py, src/foremast/pipeline/construct_pipeline_block.py, src/foremast/pipeline/construct_pipeline_block_lambda.py, src/foremast/pipeline/create_pipeline.py, tests/elb/test_elb.py, tests/test_consts.py
These changes allow to specific security groups for elb and ec2 instances per account.
Currently the only option is to set sg for all account. This gives a little more flexibility on what sg are added to a specific account.
=> Add account level security group configuration options

src/foremast/pipeline/construct_pipeline_block.py, src/foremast/pipeline/create_pipeline.py, tests/pipeline/test_create_pipeline.py
This is an attempt to break #180 into smaller PRs
This just separates out ec2 logic from create_pipeline and construct_pipeline_block. This makes it easier to then refactor so that the separate classes for s3 and lambda can be removed. Makes the calls more generic
=> Refactor Construct Pipeline Block to Segregate ec2 logic

src/foremast/pipeline/construct_pipeline_block.py
This was causing security groups to be appended multiple times and anything in pervious stages would impact later a stages. 
Create a new list each time.
=> create new list to avoid mutation errors

src/foremast/templates/infrastructure/iam/dynamodb.json.j2
For Lambda Functions to use DynamoDB as a Trigger, the IAM Role needs to have access to the `table/name/stream/` directory:
```
There was an error creating the trigger: Cannot access stream arn:aws:dynamodb:us-east-1:222572804561:table/name/stream/2017-07-28T18:53:40.930. Please ensure the role can perform the GetRecords, GetShardIterator, DescribeStream, and ListStreams Actions on your stream in IAM.
```
=> fix: Allow access to DynamoDB table/name/stream/

src/foremast/awslambda/s3_event/s3_event.py
This prevents an issue where multiple lambda triggers for the same bucket end up with conflicting SIDs.
=> fix: Create S3 lambda trigger SID with hash of rules

src/foremast/iam/construct_policy.py, src/foremast/utils/templates.py, tests/iam/test_iam_valid_json.py
We need a way to automatically validate any IAM Policy templates will render to JSON properly. We can come back to this in the future and move the logic to a `foremast validate templates iam` command or something.
=> tests: Sanity check IAM Policy templates

_docs/configuration_files/foremast_config.rst, src/foremast/consts.py, src/foremast/securitygroup/create_securitygroup.py, src/foremast/templates/configs/config.py.example, src/foremast/templates/configs/foremast.cfg.example, tests/test_consts.py, tests/test_default_security_groups.py
Works with an addition like -
```
[base]
default_securitygroup_rules = { "bastion" : [ { "start_port": "22", "end_port": "22", "protocol": "tcp" } ],
"eureka" : [ { "start_port": "8080", "end_port": "8080", "protocol": "tcp" } ] }
``` 
to foremast.cfg
=> Added ability to have default application securitygroup rules

src/foremast/awslambda/s3_event/s3_event.py
This worked as-is with Python 2.7 but apparently I didn't test it with Python 3.
=> fix: explicitly encode lambda trigger rules

_docs/configuration_files/pipeline_json/services.rest, src/foremast/templates/infrastructure/iam/rds-db.json.j2
This patch forces App Name to be used for the user name to prevent folks from specifying any user.
=> Preventing setting of username in RDS-DB.

src/foremast/securitygroup/create_securitygroup.py, tests/test_securitygroup.py
If we have self-referencing rules (aka `$self`) defined in `config.py`, then new apps will fail as there is a dependency loop going on. We can't create the sg since there is a rule referencing itself.
This changes the behavior on how we create security groups.
*New apps*
First create an sg, if none found
then update the sg with the new rules
*Existing apps*
Update sg with new rules
=> Fix issue creating security groups

src/foremast/awslambda/awslambdaevent.py, src/foremast/awslambda/s3_event/s3_event.py, src/foremast/templates/infrastructure/lambda/s3_event.json.j2, tests/lambda/test_event.py
AWS operations need to be applied to the bucket once for all events that use that bucket.
=> fix: multiple lambda s3 trigger event creation

src/foremast/utils/tasks.py, src/foremast/utils/vpc.py
We should return something useful from checking a Task status. The most useful thing we have is the status result from the poller. Also, updating some old docstrings with more information.
=> fix: Return Task status, update docstrings

src/foremast/pipeline/create_pipeline.py
This limit can be enforced in templates if necessary. It was put in as a cost saving measure but should not be hard coded in.
=> removed hardcoded image size limit

_docs/configuration_files/pipeline_json/index.rst, src/foremast/templates/infrastructure/iam/trust/rolling_role.json.j2, src/foremast/utils/get_cloudwatch_event_rule.py
Just added small docs to note that rolling is a supported pipeline type and added a missing trust file for rolling pipelines. This is the same as the ec2 trust file.
=> added docs and missing trust template for rolling pipeline

_docs/configuration_files/application_json.rst, src/foremast/autoscaling_policy/create_policy.py
This adds the ability to disable the scale-down policy. Default behavior remains the same.
=> Disable scale down

_docs/configuration_files/pipeline_json/services.rest, src/foremast/elb/create_elb.py, src/foremast/templates/infrastructure/iam/athena.json.j2, src/foremast/templates/infrastructure/iam/glue.json.j2
Athena and Glue are a bit different as there is no resource based policies. Typically, you restrict the data behind the scenes with S3 permissions.
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_athena.html
https://docs.aws.amazon.com/glue/latest/dg/api-permissions-reference.html
=> Add support for Glue and Athena to IAM Services block

src/foremast/elb/create_elb.py, src/foremast/elb/format_listeners.py, tests/elb/test_elb.py
ACM creates certs per region, this change enables users to reference certs by friendly name instead of long ARN. In doing this, we need to have backwards compatibility for both the v1 format and v2. I attempt the lookup in the v1 format first, if not we fall back to v2. 
1. Do we want to have an execution flag to default to v2 for internal teams to prevent conflicts? 
2. Working on Unit tests now.
```{
"iam": {
"stage": {
"wildcard.example.com": "arn::::example"
},
"prod": {
"wildcard.example.com": "arn:::::example"
}
},
"acm": {
"us-east-1": {
"stage": {
"wildcard.appgroup.example.com": "arn:acm:::example"
},
"prod": {
"wildcard.appgroup.example.com": "arn:acm:::example"
}
},
"us-west-2": {
"stage": {
"wildcard.appgroup.example.com": "arn:acm:::example"
},
"prod": { …
```
=> Added new tlscert_naming template format to allow support for ACM

src/foremast/securitygroup/create_securitygroup.py
We need to ensure that we do not attempt cross account security lookups
when the account is the same as the app. We should only trigger that
lookup when the app and SG are different.
=> fix: Cross acount SG within same account

src/foremast/securitygroup/create_securitygroup.py
This fixes the following error introduced during refactoring:
```
Traceback (most recent call last):
File "/tmp/workspace/pipes-pipeline-prepare/venv/bin/prepare-infrastructure", line 11, in <module>
sys.exit(prepare_infrastructure())
File "/tmp/workspace/pipes-pipeline-prepare/venv/lib/python3.6/site-packages/foremast/runner.py", line 252, in prepare_infrastructure
runner.create_secgroups()
File "/tmp/workspace/pipes-pipeline-prepare/venv/lib/python3.6/site-packages/foremast/runner.py", line 170, in create_secgroups
sgobj.create_security_group()
File "/tmp/workspace/pipes-pipeline-prepare/venv/lib/python3.6/site-packages/foremast/securitygroup/create_securitygroup.py", line 269, in create_security_group
ingress_rule = self.create_ingress_rule(app, rule)
File …
```
=> fix: We should default the env to current one

src/foremast/templates/pipeline/pipeline_wrapper.json.j2
We already have defined Pipeline types for lambda, s3 and datapipeline.
=> refactor: Remove defined types in pipeline_wrapper

_docs/configuration_files/foremast_config.rst
Fixes the alignment of the `types` option on this page:
http://foremast.readthedocs.io/en/latest/configuration_files/foremast_config.html
=> docs: Fix header for types option

src/foremast/runner.py, tests/test_runner.py
This allows users to create custom pipeline type and not need to make
code updates for those new types to work.
=> refactor: Fallback to default pipeline for unknown types

src/foremast/pipeline/create_pipeline.py
We do this with stage creation but I need this data during wrapper creation as well so that we can disable a trigger.
This just passes everything in `pipeline.json` to wrapper creation so that extra fields can be added without touching foremast source in the future.
=> pass all pipeline data to wrapper creation

src/foremast/pipeline/create_pipeline_datapipeline.py, src/foremast/pipeline/create_pipeline_lambda.py, src/foremast/pipeline/create_pipeline_s3.py
This was added for ec2 pipelines in https://github.com/gogoair/foremast/pull/266 but forgot to update it in the other pipeline types.
=> disabled trigger for other pipelines besides just ec2

src/foremast/configs/prepare_configs.py, src/foremast/templates/configs/configs.json.j2, tests/configs/test_prepare_configs.py
This PR adds support for overlaying region specific configs but also keeps all backwards compatibility. From this PR, nothing uses the region specific configs and those will come in a latter update. This PR also abstracted out some logic from the `process_git_configs` and `process_runway_configs` functions. These were almost identical so I moved them under a shared function to reduce duplicate code. 
Examples of new configs:
Below config is the application-master-stage.json for an app. min_inst and max_inst should be different for us-west-2. 
```{
"security_group": {
"description": "something useful",
"elb_extras": [],
"instance_extras": ["offices_all", "sumologic"]
},
"app": {
"instance_type": "t2.small",
"app_description": "Edge Forrest Demo application",
"instance_profile": …
```
=> Add support for combining region specific configs

src/foremast/dns/create_dns.py, src/foremast/runner.py
We should only update the global dns record when it matches the primary region.
This addresses a problem where the secondary, region specific, domain was updating the global dns record.
=> Fix failover dns

src/foremast/securitygroup/create_securitygroup.py
This removes the warning we have for apps using `app_a` and `app_b` in the security group section.
This warning has been in place for over a year and its about time we remove it.
=> fix: Remove warning of example security groups

src/foremast/autoscaling_policy/create_policy.py
This is mostly a cosmetic fix, however, it should help with troubleshooting issues.
Old view:
```
2018-01-29 14:49:34,886 [INFO] foremast.utils.banners:banner:39 - ================================================================================
2018-01-29 14:49:34,886 [INFO] foremast.utils.banners:banner:40 -                             Creating Scaling Policy                             
2018-01-29 14:49:34,886 [INFO] foremast.utils.banners:banner:41 - ================================================================================
2018-01-29 14:49:35,163 [INFO] foremast.autoscaling_policy.create_policy:get_all_existing:162 - Checking for existing scaling policy
2018-01-29 14:49:35,552 [INFO] foremast.autoscaling_policy.create_policy:get_all_existing:170 - Found policies on …
```
=> Minor ASG Policy fixes

requirements.txt, src/foremast/configs/prepare_configs.py, src/foremast/utils/lookups.py, tests/test_ami_lookup.py, tests/utils/test_file_lookups.py, tox.ini
We should use version 4 of gitlab api. The api v3 will be removed in a future version later this year.
=> Use gitlab v4 api

src/foremast/templates/pipeline/pipeline_wrapper.json.j2
I included a custom reference to a stage in 2556e13d387b00bc45654db25167f488cf80919e.
The `stage-tagger.json.j2` does not exist and this removes that reference.
=> Remove reference to invalid stage

src/foremast/s3/s3apps.py
This was something that got missed while adding region specific configs.
=> fixed s3 app dns ttl issue with region specific configs

src/foremast/configs/outputs.py
Since we moved to dicts for the `regions` block, the default in our templates gets put in even if excluded in application configs. This makes sure to only use the regions in the application config. If not provided in the application config, it will use the default in the templates.
=> overrides regions in templates with regions in configs

src/foremast/utils/templates.py, tests/iam/test_iam_valid_json.py
We should show the fully qualified path of the templates that are used.
Old
```
2018-01-29 15:29:18,160 [INFO] foremast.utils.templates:get_template:84 - Rendering template /data/git/github/foremast/src/foremast/utils/../templates/infrastructure/autoscaling_policy.json.j2
```
New
```
2018-01-29 15:22:15,280 [INFO] foremast.utils.templates:get_template:86 - Rendering template /data/git/github/foremast/src/foremast/templates/infrastructure/autoscaling_policy.json.j2
```
=> fix: Use fully qualified path to file

requirements.txt, src/foremast/securitygroup/create_securitygroup.py, tests/test_securitygroup.py
We have the ability add default security group rules via our `config.py` files.
There are scenarios where an application (via `application.json`) needs to add a rule, which correspond to one already defined in `config.py`. In those scenarios, the default definition from `config.py` will win and those definitions will be used instead of what an application has defined.
In does the following:
```
DEFAULT = {'test_app': [{'start_port': 31,'end_port': 31,}]}
APP = {'test_app': [{'start_port': 30,'end_port': 30,}]}
OLD_BEHAVIOR =  {
'test_app': [
{
'start_port': 31,
'end_port': 31,
}
]
}
NEW_BEHAVIOR =  {
'test_app': [
{
'start_port': 30,
'end_port': 30,
},
{
'start_port': 31,
'end_port': 31,
}
]
}
```
=> Better merge of default and application security group rules.

src/foremast/templates/infrastructure/iam/athena.json.j2, src/foremast/templates/infrastructure/iam/glue.json.j2
- Athena now includes glue:Get* as this is now required once Athena's data catalog is upgraded.
- Glue was converted to generic Get* as this might need to be tweaked in
the future
=> Updated Athena and Glue permissions

_docs/configuration_files/application_json.rst, src/foremast/s3/s3deploy.py, tests/s3/test_s3deploy.py
This enabled the ability to do "flat" s3 deployments, flat meaning no version and no LATEST directory. The contents are uploaded in the exact structure as the artifact. 
This does DELETE everything else in the bucket. It is expected, but potentially dangerous bahavior. Is it worth coming up with some protection? 
This works by simply setting "deploy_strategy" to "flat"  in application-master-env.json.
=> Flat s3 deployments

src/foremast/runner.py, src/foremast/s3/s3apps.py, src/foremast/s3/s3deploy.py, tests/s3/test_s3deploy.py
This PR will use different naming convention for region specific buckets outside the primary region. The reason the primary region does not have a different name is for backwards compatibility.
=> Updates bucket naming to include region if not primary region

src/foremast/s3/s3apps.py
checks that non-east buckets exist before trying to create. 
https://stackoverflow.com/questions/10346378/boto-s3-error-bucketalreadyownedbyyou description of why this logic is necessary.
=> fixed issue with non-east buckets already existing and giving errors

src/foremast/templates/infrastructure/iam/s3.json.j2, tests/iam/test_iam_construct.py
It appears the s3 template seems to have a reference so some example bucket. I can't find a reason for it to be there so I aligned it with the dynamodb.json template with the built in Jinja2 last feature.
=> Clean-up: Example S3 Bucket Name in Templates

_docs/configuration_files/application_json.rst
Just a quick small docs fix. The key used in the example is "environment" but should be "lambda_environment".
=> docs: Fixed wrong key in lambda_environment example for application json

src/foremast/consts.py
Need to start using the configurations in the `dict` form. The way `configparser.ConfigParser` works, it squashes all configuration values into `str` and negates some of the benefits of using Dynamic Configurations with `config.py`.
In particular, I'm concerned with the Application Format configurations in `config.py`. Because I want to use some bizarre string formatting, I need to override the `str.format()` behaviour using a Subclass.
```python
class AppName(str):
"""Custom Application name manipulation."""
def format(self, *args, **kwargs):
"""Override default formatting."""
repo = kwargs['repo']
first, *rest = repo.split('-')
camel = [word.capitalize() for word in rest]
app_name = ''.join([first, *camel])
return super().format(*args, app_name=app_name, **kwargs)
CONFIG = {
'formats': …
```
=> fix: Use dict configs

.travis.yml
One `deploy` block will deploy Commits to the `master` Branch. The other block will deploy Tags. I can't figure out a way to combine these into one block due to the way Travis `deploy` works where specifying `tags` ignores `branch` and specifying `branch` ignores `tags`.
There is a small race condition if Tags are pushed faster than Travis can start building the Branch Commit. This results in both Branch and Tag builds trying to deploy the same Tagged version and one will show as false failure.
Example false failure:
* `master` Commit build created: https://travis-ci.org/e4r7hbug/foremast/builds/389587423
```
Uploading distributions to https://test.pypi.org/legacy/
Uploading foremast-3.46.3-py2.py3-none-any.whl
100% 206k/206k [00:01<00:00, 109kB/s]
```
* Tag build: …
=> feat: Deploy with Travis

_docs/configuration_files/foremast_config.rst, src/foremast/consts.py, src/foremast/pipeline/construct_pipeline_block.py, src/foremast/pipeline/create_pipeline.py, tests/test_consts.py
Need a way to inject custom Pipeline Types that are deployed with EC2.
=> refactor: Support overriding EC2 Pipeline Types

_docs/configuration_files/foremast_config.rst, src/foremast/consts.py, src/foremast/pipeline/create_pipeline.py, src/foremast/pipeline/create_pipeline_datapipeline.py, src/foremast/pipeline/create_pipeline_lambda.py, src/foremast/pipeline/create_pipeline_s3.py, src/foremast/templates/configs/config.py.example, src/foremast/templates/configs/foremast.cfg.example, src/foremast/templates/configs/pipeline.json.j2, src/foremast/templates/pipeline/trigger-jenkins.json.j2
- Needed for Fiat enabled applications to specify service account
=> Support to run pipelines using a default `Run As User`

src/foremast/configs/outputs.py, src/foremast/iam/create_iam.py, src/foremast/pipeline/construct_pipeline_block.py, src/foremast/pipeline/construct_pipeline_block_datapipeline.py, src/foremast/pipeline/construct_pipeline_block_lambda.py, src/foremast/pipeline/construct_pipeline_block_s3.py, src/foremast/pipeline/create_pipeline.py, src/foremast/pipeline/create_pipeline_datapipeline.py, src/foremast/pipeline/create_pipeline_lambda.py, src/foremast/pipeline/create_pipeline_s3.py, src/foremast/securitygroup/create_securitygroup.py, tests/iam/test_iam_create.py
This allows the object to be accessible to some templates via the `generated` object in jinja.
For example, in `templates/configs/configs.json.j2`, something like this can be added:
```
"lambda_role": {{ generated.app_name() }},
```
This does depend on version 1.9.0 and above of `gogo-utils`.
=> Send `gogoutils.Generator` to templates

README.rst, _docs/pipeline_examples.rst, setup.py
This is to fix some of the URLs after the org move from `gogoair/foremast` to `foremast/foremast`.
=> Fix urls after org move

src/foremast/app/create_app.py
Must have forgot to pass the custom configuration naming strings.
See also: #314, 783277def281cfa772c633e859b7dd7d5d162f82
=> fix: Need to pass configuration format strings

src/foremast/utils/tasks.py
Instead of rewriting a custom task module, I wish to update the existing task module to support passing of additional custom URI strings to tasks endpoint. This maintains feature parity but enables overriding custom tasks.
=> Adding support for passing custom task uri

src/foremast/pipeline/construct_pipeline_block.py
This is useful for supporting custom variables being passed to the
Pipeline Wrapper Template.
=> feat: Allow Wrapper passthrough keyword arguments

src/foremast/consts.py, src/foremast/utils/subnets.py, src/foremast/utils/vpc.py
Latest version of Spinnaker is returning additional subnets and VPCs. We have a strict conditional on specific key/values being present, and they might not always be present.
In addition, fixing issue with ast.literal_eval. Running into a reported bug after upgrading system Python to Python 3.7.2
=> Latest Spinnaker release returns additional results with missing keys

_docs/configuration_files/foremast_config.rst, src/foremast/configs/prepare_configs.py, src/foremast/consts.py, src/foremast/pipeline/clean_pipelines.py, tests/test_consts.py
Not everyone will call their application repo "runway/", this enables folks to override this while still retaining the default "runway/" behavior today.
=> feat: Added support for custom runway directory name

_docs/configuration_files/application_json.rst
The default timeout is not 3600, you can't even specify more than 900 currently. Added a doc in case AWS increases the timeout as well.
=> Lambda Docs: Timeout Invalid

_docs/configuration_files/pipeline_json/services.rest, src/foremast/templates/infrastructure/iam/datapipeline.json.j2
To have an event driven architecture its cool to use AWS lambda. When an S3 object is pushed today support is not available to activate a data pipeline. 
This new feature will add the capability.
=> adding support to allow data pipeline in service block 

src/foremast/consts.py
Pipeline type "manual" is supported and included in documentation, however it is not in the default allowed pipeline types resulting in an exception when trying to use the feature.  This PR adds the manual pipeline type to the allowed pipelines.
=> fix: Added 'manual' pipeline type to default allowed types

src/foremast/utils/subnets.py, src/foremast/utils/vpc.py
In both cases, we are trying to log keys that might not exist. 
Spinnaker's response has come a long way since this was implemented and offers quite a bit of what we were doing here. Logging the response body looks like:
`{"account":"some_account", "cloudProvider":"some_provider", "deprecated":false, "id":"some-vpcid", "name":"some_tag_name", "region":"some_region"}`
=> fix: Unknown values in logging

src/foremast/s3/s3deploy.py
The new feature for s3 pipeline added ability to override name with existing s3 buckets. However, it missed the s3deploy step.
=> adding bucket_name for deploy option

src/foremast/consts.py
When setting `FOREMAST_CONFIG_FILE=config2.py` I noticed it was still always loading `config.py`.  
The code to import the 'config' module was adding the config2.py's directory then loading the module, but since both config2.py and config.py are in the same directory (in my case) the incorrect one was loaded.  
This PR fixes the bug by loading the config module from a filepath rather than a directory.
The solution only works in Python 3.5+ according to [StackOverflow](https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path).
=> Fixed bug causing incorrect config py to be loaded

requirements.txt, src/foremast/utils/google_iap.py
Google Cloud supports a partially automated deployment of Spinnaker using Google Identity Aware Proxy for authentication.   There is only one Gate endpoint available, making it difficult to support Google IAP and x509 Auth.
This PR adds a util function to authenticate against Google IAP using an appropriately configured Google Cloud Service Account.  The function returns the a JWT which can be used to authenticate against Spinnaker.
Usage:
```python
svc_account_creds_path='/my/path/svc-account.json'
iap_client_id ='my-client-id-from-google'
my_token = get_google_iap_bearer_token(iap_client_id, svc_account_creds_path)
```
=> Added util function for Google Identity Aware Proxy tokens

.travis.yml, tox.ini
After discussion, we are dropping support for Python 3.4. If there is no strong disagreement, we should consider 3.5. Thoughts?
=> refactor: Removed support for Python versions 3.4 and 3.5

src/foremast/app/aws.py, src/foremast/templates/infrastructure/app_data.json.j2
Looking at the latest Spinnaker Release, the create application call does not expect an iterated loop of accounts. This is breaking some extensions when it comes to manual pipelines. In order to retain backwards compatibility we are leaving a default list of accounts but this isn't used. Here is the most recent JSON payload to createApplication:
```{
"job": [
{
"type": "createApplication",
"application": {
"cloudProviders": "aws",
"instancePort": 80,
"providerSettings": {
"aws": {
"useAmiBlockDeviceMappings": false
}
},
"name": "testapp",
"email": "test@test.com",
"description": "Test"
},
"user": "example@example.com"
}
],
"application": "testapp",
"description": "Create Application: testapp"
}
```
=> fix: Unneeded loop of accounts on app creation

_docs/configuration_files/application_json.rst, src/foremast/awslambda/awslambda.py, src/foremast/templates/configs/configs.json.j2, tests/lambda/test_aws.py, tests/lambda/test_event.py
Currently foremast does not support Dead Letter Queue Configuration as part of Lambda Pipeline. 
A key challenge that Lambda users will face in the pipeline is the handling of exceptions. Some examples include:
- Notifications of when a function fails e.g. via an SNS handler
- Queue messages that can be reviewed by developers for root cause such as SQS
=> adding initial support for dlq

_docs/configuration_files/application_json.rst
For some reason docs were missing lambda_concurreny_limit docs. Add details to help educate users
=> adding docs for concurrency limits

_docs/lambda/lambda_events.rst, setup.py, src/foremast/awslambda/cloudwatch_event/cloudwatch_event.py
There have been some significant enhancements to how Lambda Events work, no longer do you just need to use cron schedules. You can actually use Lambda Event patterns to generate triggers of events based on cloudwatch rules!
=> feat: Lambda Event Pattern Support

_docs/configuration_files/foremast_config.rst, src/foremast/utils/gate.py
This PR:
- Adds support for github bearer token authentication against `gate`
- Update documentation to show an example of this feature
- Fix `code-block` [identation issue](https://foremast.readthedocs.io/en/stable/configuration_files/foremast_config.html#gate-authentication-keys) on documentation.
=> feat: Add github token gate authentication

src/foremast/awslambda/cloudwatch_event/cloudwatch_event.py
According to the boto3 logs, statement_id just needs to be something unique: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.add_permission
When generating statementId, the end result in the current version is something like "foremast-XXXXXXX_cloudwatch_XXXXXXXX_YYYYY" where XXXXXXXX is the app name and YYYYY is the cloudwatch event name (see line 61 for where rule_name is set).
With this code change, you'll eliminate the first XXXXXXXXX. This will reduce the occurrences of the following error for end users while keeping the statementId universally unique:
2019-12-14 23:47:38,953 [DEBUG] foremast.utils.awslambda:add_lambda_permissions:131 - Add permission error: An error occurred (ValidationException) when calling the AddPermission …
=> Update cloudwatch_event.py to reduce length of statement_id

_docs/configuration_files/application_json.rst
```json
"lambda_tracing": {
"TracingConfig": "Active"
}
```
The above configuration example results in the following error from the underlying `boto3` lambda client:
```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in TracingConfig: "TracingConfig", must be one of: Mode
```
Instead, the client expects the following structure: 
```
"lambda_tracing": {
"Mode": "Active" | "Passthrough"
}
```
Updating the `application-master-*.json` documentation accordingly.
=> docs: Update faulty lambda-tracing example JSON

src/foremast/runner.py, src/foremast/s3/s3deploy.py, tests/s3/test_s3deploy.py
- Allows mirroring of git branches to s3 buckets using versioned folders
- refactor: renamed logic from uri to path for simplicity and understanding
- refactor: removed dependency on mirror (bool) to deploy_strategy (str)
=> feat: Added support for branch based S3 Deployments

_docs/configuration_files/application_json.rst, src/foremast/awslambda/awslambda.py, src/foremast/templates/configs/configs.json.j2, tests/lambda/test_aws.py, tests/lambda/test_event.py
Closes #403 
This simple feature provides the ability for developers to control destinations for success and failure if desired. 
For example: If a lambda function fails you may want to run an exception handler lambda utility that performs clean up.
=> feat: First commit of lambda destinations

.travis.yml
This PR changes the following commands:
- Adds `os` explicit call
- Removes deprecated `sudo` command
- Moves the cache command to after script to replicate [the order of cache.](https://docs.travis-ci.com/user/caching#build-phases)
- Moves notifications to the end since is the last action taken
- Renames deprecated `matrix` for `jobs`
- Renames deprecated `user` for `username`
=> Update Travis Syntax

_docs/configuration_files/application_json.rst, _docs/configuration_files/pipeline_json/lambda.rest, src/foremast/awslambda/awslambda.py, src/foremast/templates/configs/configs.json.j2, tests/lambda/test_aws.py, tests/lambda/test_event.py
This allows teams to specify how many subnets they want associated to their lambda functions. Due to a limitation of AWS' recent Hyperplane changes, accounts are limited to 250 ENIs. This means if you deploy a Lambda in a VPC with 3 Subnets and a unique SG, each lambda will make 3 ENIs. We burned through the limit rather fast and I am sure other users of foremast may soon do the same.
By doing this, it enables teams to specify how resilient they need lambdas to be, by default and for  backwards compatibility, we default to all subnets. Teams can reduce this to 1 or as many needed.
=> feat: lambda_subnet_count to limit subnets associated to VPC Enabled Lambda

_docs/lambda/lambda_events.rst, src/foremast/autoscaling_policy/create_policy.py, src/foremast/awslambda/api_gateway_event/api_gateway_event.py, src/foremast/awslambda/awslambdaevent.py, src/foremast/utils/kayenta.py
Issue:
- Foremast was hardcoded to set API gateway integration to "AWS". 
- Developers were unable to set integration type for API Gateways.
Fix:
- Add new setting "api_type" to allow users to set integration type.
- Default to "AWS" if setting not set.
=> Added support for lambda gateway integration type

src/foremast/pipeline/create_pipeline_manual.py
It seems `str.lstrip("templates://")` is sometimes stripping an additional character.  For example `templates://pipline_stage.json` is being stripped to `ipline_stage.json` and causing pipeline failures.  
Not entirely sure why, but we already know the file path starts with `templates://` at this point in the code so the easy fix is to remove it using Python's substring syntax instead.
=> fix: bug stripping too many template path chars

src/foremast/gcp_iam/create_iam_resources.py
Fixes a `KeyError` when checking for the existence of a GCP service account in a GCP project with 0 service accounts.
=> fix: KeyError when retreiving service accounts in a new project

src/foremast/gcp_iam/create_iam_resources.py, src/foremast/utils/gcp_environment.py
Fixes issue where Foremast does not see existing service accounts.  Cause was pagination in the list service accounts API. 
Changes:
* GCP get service account uses get svc account API (instead of list svc accounts api)
* Disables cache discovery on all GCP API objects as this fills the log with warning level exceptions ([see issue](https://github.com/googleapis/google-api-python-client/issues/299))
=> fix: Existing svc accounts not being found in GCP IAM

_docs/configuration_files/advanced_usages/GCP Service Account IAM Policies.rst, src/foremast/gcp_iam/create_iam_resources.py, src/foremast/runner.py
GCP Service Account IAM Policy Jinja template had app, group and env passed in.  Unfortunately I mistook app for the shorthand project/repo name.  This PR adds the repo name as well.
=> fix: Missing repo argument for GCP Svc Account IAM policy

_docs/configuration_files/application_json.rst, src/foremast/cloudfunction/cloud_functions_client.py, src/foremast/runner.py
GCP Cloud Functions using HTTP Triggers support anonymous/unauthenticated access as well as authenticated access.  With authenticated access it is also possible to grant access to invoke the cloud function to specific groups, users and service accounts.  Currently Foremast does not support any of these features, so all functions default to authenticated users only who have correct permissions on the entire project the function is in.
This PR allows opting in to unauthenticated access, as well as adding IAM bindings to grant access to a single function.
=> feat: IAM access control for Cloud Functions

_docs/configuration_files/application_json.rst
CloudFunctions timeout expects a String but docs are calling for int. Fixing!
=> fix: Docs issue with CloudFunction timeouts

_docs/configuration_files/application_json.rst, src/foremast/templates/configs/configs.json.j2, src/foremast/templates/pipeline/stage-judgement-nonprod.json.j2, src/foremast/templates/pipeline/stage-judgement-promote-s3-nonprod.json.j2, src/foremast/templates/pipeline/stage-judgement-promote-s3-prod.json.j2
Today, pipeline stages timeout after 72 hours. This is done to maintain a clear queue and also performance to prevent stale pipelines. Most pipelines get hung up on approval stages, and as a result sometimes clutter a deployment view.
This feature enables the ability to maintain cleaner pipelines and fail faster than default 72 hour timeout by specifying an approval stage timeout in milliseconds (based on API).
=> feat: Added support to timeout approval stages after specified time

src/foremast/cloudfunction/cloud_functions_client.py
Cloud function triggers should be specified without the project id:
```
"cloudfunction_event_trigger": {
"resource": "buckets/my-great-bucket",
"event_type": "google.storage.object.archive"
},
```
Foremast then adds the project id automatically based on the project it is deploying to.  If a developer accidentally puts the project Id in their pipeline files, this produces something like: `projects/myproject/projects/myproject/buckets/my-great-bucket` leading to an error from the Google API. 
The Google API error is not very clear, so this PR adds a more clear error message from Foremast.
=> fix: better error message when cloud function event resource has duplicate project id

_docs/configuration_files/pipeline_json/index.rst, _docs/configuration_files/pipeline_json/notifications.rest, _docs/configuration_files/pipeline_json/pipeline_notifications.rest, src/foremast/templates/configs/pipeline.json.j2, src/foremast/templates/pipeline/pipeline_notifications.json.j2, src/foremast/templates/pipeline/pipeline_wrapper.json.j2
Foremast supports Spinnaker pipeline failure notifications for Slack and Email via the `notifications` block in `pipeline.json`.  
Today Spinnaker has a long list of features not supported by Foremast including Microsoft Teams, Google Chat, Pub/Sub, custom messages and triggering based on pipelines starting, failing and completing.  The new alpha features for Spinnaker Plugins also allows custom notification options to be defined ([example](https://github.com/spinnaker-plugin-examples/notificationPlugin)).  This PR adds support for any notification option.
**Deprecation of notifications block**
To achieve support for any notification option a new syntax was needed which mirrors the Spinnaker syntax.  This new option can be defined in `pipeline.json` using the `pipeline_notifications` …
=> feat: Pipeline notification support for all providers and options

_docs/configuration_files/application_json.rst
Added missing docs for enabling Cloud Function's retry on failure policy
=> chore: Added missing retry policy for cloud functions

src/foremast/pipeline/create_pipeline_manual.py, src/foremast/pipeline/jinja_functions.py, src/foremast/utils/templates.py
This PR allows manual templates to reference Foremast's default Jinja templates and variables used in other pipeline types.
Changes:
* Manual templates now use the same Jinja2 Environment as all other templates
* Manual templates now have access to Jinja2 variables exposed to other templates (e.g. `data.app.pipeline`, `data.app.appname`, etc)
* Existing manual template variables marked as deprecated: `trigger_job`, `group_name`, `app_name`, `repo_name`.  These are now passed in consistently with non-manual templates.  Leaving them in for now for backwards compatibility.
Example:
In a manual template I can now use Foremast's pipeline notification features by doing something like:
```jinja2
{
"notifications": {% include "pipeline/pipeline_notifications.json.j2" %},
}
```
------------
I …
=> feat: Manual templates now support default stage templates

_docs/configuration_files/gcp_environments.rst, src/foremast/gcp_iam/create_iam_resources.py
Im not entirely sure if this has changed, or if I missed this in testing - but GCP Project labels do not allow commas.  This means it's not possible to support multiple groups in the `foremast_groups` label.  
This PR changes from a comma separated list to a double underscore separated list.  Chose double underscore as it seems uncommon enough that it won't overlap with anything else.
Old (won't work):
New:
=> fix: GCP foremast_groups label now double underscore separated

src/foremast/iam/create_iam.py, src/foremast/iam/resource_action.py
Fixes #400, but marking as draft as I think some discussion is needed.  As noted in the issue, AWS may reject an IAM Policy document which will be logged by Foremast but this will not cause a raised error.  This leads to pipelines looking valid/successful, but upstream the app being deployed will have permissions issues as the IAM policy was rejected.
This comes down to the function `resource_action` failing silently except for `AccessDenied` errors.  This PR updates this to allow disabling silent errors with no change to the default.
I think it would make more sense to never fail silently (or change the default not to fail silently) but I'm not sure what the reason was for the original design or what the implications would be.  Thoughts on that?
=> fix: AWS IAM put role policy no longer fails silently

.travis.yml, _docs/configuration_files/application_json.rst, src/foremast/awslambda/awslambda.py, src/foremast/s3/s3apps.py, src/foremast/templates/configs/configs.json.j2, src/foremast/templates/pipeline/stage-deploy.json.j2, tests/lambda/test_aws.py
Initial commit getting custom tags to work in deploy stage. Need to continue and add support for other deploy types and custom infra.
=> feat: Added support for custom tags on ec2 deploys

.github/workflows/githubactions-pypipublish.yml, _docs/configuration_files/application_json.rst, src/foremast/awslambda/awslambda.py, src/foremast/templates/configs/configs.json.j2, tests/lambda/test_aws.py
Defaulting to legacy "internal" setting, but overriding to allow teams to set specific subnet purpose su
=> Support for Specifying Lambda Subnet Purpose

.github/stale.yml
Adding [Stale bot from Github](https://github.com/marketplace/stale).  I've already authorized via the GitHub UI, just need this config to kick it off.  Open to discussion on the config.
=> chore: adding stale bot

src/foremast/awslambda/awslambda.py, src/foremast/cloudfunction/cloud_functions_client.py, src/foremast/utils/__init__.py, src/foremast/utils/backoff.py
With Foremast now uploading code changes for Lambdas we are seeing some occasional `ResourceConflictErrors`, this is a change AWS is rolling out [documented here](https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html).  If a lambda is in a pending update state, any API calls to modify the lambda will fail.  This PR addresses that:
* Added exponential backoff helper for re-use in lambda and cloud function pipelines
* Split lambda create/update methods into smaller functions with individual API calls and backoffs
* Added backoff retry to any lambda class methods making API calls that could cause `ResourceConflictError`
=> fix: expontential backoff for lambda resource update conflicts
